DROP TABLE IF EXISTS `comentarios`;
CREATE TABLE IF NOT EXISTS `comentarios` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(220) COLLATE UTF8MB4_UNICODE_CI,
  `comentario` VARCHAR(220) COLLATE UTF8MB4_UNICODE_CI,
  `created_at` TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_UNICODE_CI;


DROP TABLE IF EXISTS `formulario`;
CREATE TABLE IF NOT EXISTS `formulario` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(220) COLLATE UTF8MB4_UNICODE_CI,
  `email` VARCHAR(220) COLLATE UTF8MB4_UNICODE_CI,
  `recomend` VARCHAR(220) COLLATE UTF8MB4_UNICODE_CI,
  `fases` VARCHAR(220) COLLATE UTF8MB4_UNICODE_CI,
  `motivo`VARCHAR(220) COLLATE UTF8MB4_UNICODE_CI,
  `texto`VARCHAR(220) COLLATE UTF8MB4_UNICODE_CI,
  `created_at` TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_UNICODE_CI;


INSERT INTO comentarios(nome, comentario) VALUES('Clara', 'Gostei muito do jogo!');
INSERT INTO comentarios(nome, comentario) VALUES('Jorge', 'Não gostei!');
INSERT INTO comentarios(nome, comentario) VALUES('Anonimo', 'Achei fácil');

SELECT * FROM formulario;